version: '3.9'
services:
  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules

  server:
    build: ./server
    container_name: server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      - CGO_ENABLED = 1

  db:
    image: "postgres:${POSTGRES_VERSION}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}

  rabbitmq:
    image: "rabbitmq:3.12-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
