// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	AddContestCreators(ctx context.Context, arg AddContestCreatorsParams) (ContestCreator, error)
	CreateContest(ctx context.Context, arg CreateContestParams) (Contest, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, username string) error
	GetContest(ctx context.Context, id int64) (Contest, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListContests(ctx context.Context, arg ListContestsParams) ([]Contest, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
